export const AppRoute = {
    login: "auth/login",
    dashboard: "dashboard",
    manageUser: "manage-users",
    manageProject: "manage-projects",
    manageBanks: "manage-banks",
    manageWorkArea: "manage-workarea",
    manageTrain: "manage-train",
    manageZone: "manage-zone",
    manageSystem: "manage-system",
    manageSubSystem: "manage-subsystem",
    manageDocumentType: "manage-documentType",
    manageProcess: "manage-process",
    manageSubProcess: "manage-subProcess",
    manageStream: "manage-stream",
    manageReferenceDocument: "manage-referenceDocument",
    manageEquipmentCode: "manage-EquipmentCode",
    manageManufacturer: "manage-Manufacturer",
    manageFailState: "manage-FailState",
    manageTagTypes: "manage-TagTypes",
    manageTagDescriptors: "manage-TagDescriptors",
    manageDeviceModel: "manage-DeviceModel",
    manageDeviceType: "manage-DeviceType",
    manageNatureOfSignal: "manage-NatureofSignal",
    manageTagFields: "manage-TagFields",
    manageTag: "manage-Tags",
    manageJunctionBox: "manage-JunctionBox",
    managePanel:"manage-Panel",
    manageSkid:"manage-Skid",
    manageStand:"manage-Stand",
    instrumentList: "instrument-list",
    nonInstrumentList: "non-instrument-list",
    manageDevice: "manage-Device",
    manageHierarchy: "manage-hierarchy",
    manageLogs: "manage-logs",
    manageImport: "manage-import",
    viewDevice: "view-Device",
    manageReports:"manage-reports",
    viewReport:"view-reports",
    menuManangement: "menu-management",
    roleManangement: "role-management",
    permissionManangment: "permission-management",
    userProfile: "user-profile",
    changePassword: "change-password",
}