using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ICMD.EntityFrameworkCore.Migrations
{
    /// <inheritdoc />
    public partial class UpdateViewInstrumentListLive : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DO $$
BEGIN

DROP VIEW public.""View_OMItem_InstrumentList"";
DROP VIEW public.""View_CountDPPADevices"";
DROP VIEW public.""View_NatureOfSignalValidationFailures"";

DROP VIEW public.""View_InstrumentListLive"";

CREATE OR REPLACE VIEW public.""View_InstrumentListLive""
 AS
SELECT ""View_Device_Instruments"".""Id"" AS ""DeviceId"",
    ""View_Device_Instruments"".""ProcessName"" AS ""Process No"",
    ""View_Device_Instruments"".""SubProcessName"" AS ""Sub Process"",
    ""View_Device_Instruments"".""StreamName"",
    ""View_Device_Instruments"".""EquipmentCode"" AS ""Equipment Code"",
    ""View_Device_Instruments"".""SequenceNumber"" AS ""Sequence Number"",
    ""View_Device_Instruments"".""EquipmentIdentifier"" AS ""Equipment Identifier"",
    ""View_Device_Instruments"".""TagName"",
	""View_Device_Instruments"".""Type"" AS ""Device Type"",
    ""View_Device_Instruments"".""IsInstrument"",
	MAX(CASE WHEN h.""Instrument"" = false THEN pt.""TagName"" END) AS ""Connection Parent Tag"",
	MAX(CASE WHEN h.""Instrument"" = true THEN pt.""TagName"" END) AS ""Instr Parent Tag"",
    ""View_Device_Instruments"".""ServiceDescription"" AS ""Service Description"",
    ""View_Device_Instruments"".""LineVesselNumber"" AS ""Line / Vessel Number"",
    NULL::text AS ""Plant"",
    NULL::text AS ""Area"",
    ""View_Device_Instruments"".""VendorSupply"" AS ""Vendor Supply"",
    skidtag.""TagName"" AS ""Skid Number"",
    standtag.""TagName"" AS ""Stand Number"",
    ""View_Device_Instruments"".""Manufacturer"",
    ""View_Device_Instruments"".""Model"" AS ""Model Number"",
    attrs.""CalibratedRangeMin"" AS ""Calibrated Range (Min)"",
    attrs.""CalibratedRangeMax"" AS ""Calibrated Range (Max)"",
    attrs.""CalibratedRangeUnits"" AS ""CR Units"",
    attrs.""ProcessRangeMin"" AS ""Process Range (Min)"",
    attrs.""ProcessRangeMax"" AS ""Process Range (Max)"",
    attrs.""ProcessRangeUnits"" AS ""PR Units"",
    attrs.""RLPosition"" AS ""RL / Position"",
    docs.""DatasheetNumber"" AS ""Datasheet Number"",
    docs.""SheetNumber"" AS ""Sheet Number"",
    docs.""HookupDrawing"" AS ""Hook-up Drawing"",
    docs.""TerminationDiagram"" AS ""Termination Diagram"",
    docs.""PIDNumber"" AS ""P&Id Number"",
    docs.""LayoutDrawing"" AS ""Layout Drawing"",
    docs.""ArchitecturalDrawing"" AS ""Architectural Drawing"",
    docs.""FunctionalDescriptionDocument"" AS ""Functional Description Document"",
    docs.""ProductProcurementNumber"" AS ""Product Procurement Number"",
    jbtag.""TagName"" AS ""Junction Box Number"",
    ""View_Device_Instruments"".""NatureOfSignalName"" AS ""Nature Of Signal"",
    ""View_Device_Instruments"".""FailStateName"" AS ""Fail State"",
    attrs.""GSDType"" AS ""GSD Type"",
    attrs.""ControlPanelNumber"" AS ""Control Panel Number"",
    attrs.""PLCNumber"" AS ""PLC Number"",
    attrs.""PLCSlotNumber"" AS ""PLC Slot Number"",
    ""panelTag"".""TagName"" AS ""Field Panel Number"",
    attrs.""DPDPCoupler"" AS ""DP/DP Coupler"",
    attrs.""DPPACoupler"" AS ""DP/PA Coupler"",
    attrs.""AFDHubNumber"" AS ""AFD / Hub Number"",
    attrs.""RackNo"" AS ""Rack No"",
    attrs.""SlotNo"" AS ""Slot No"",
    attrs.""ChannelNo"" AS ""Channel No"",
    attrs.""DPNodeAddress"" AS ""DP Node Address"",
    attrs.""PANodeAddress"" AS ""PA Node Address"",
    ""View_Device_Instruments"".""Revision"",
    ""View_Device_Instruments"".""RevisionChanges"" AS ""Revision Changes / Outstanding Comments"",
    ""View_Device_Instruments"".""Zone"",
    ""View_Device_Instruments"".""Bank"",
    ""View_Device_Instruments"".""Service"",
    ""View_Device_Instruments"".""Variable"",
    ""View_Device_Instruments"".""Train"",
    ""View_Device_Instruments"".""WorkAreaPack"" AS ""Work Area Pack"",
    ""View_Device_Instruments"".""System"" AS ""System Code"",
    ""View_Device_Instruments"".""SubSystem"" AS ""SubSystem Code"",
    ""View_Device_Instruments"".""HistoricalLogging"" AS ""Historical Logging"",
    ""View_Device_Instruments"".""HistoricalLoggingFrequency"" AS ""Historical Logging Frequency"",
    ""View_Device_Instruments"".""HistoricalLoggingResolution"" AS ""Historical Logging Resolution"",
    ""View_Device_Instruments"".""IsDeleted"",
    ""View_Device_Instruments"".""ProjectId"",
    ""View_Device_Instruments"".""IsActive""
   FROM ""View_Device_Instruments""
     CROSS JOIN LATERAL ""fnGetDeviceAttributesInColumns""(""View_Device_Instruments"".""Id"") attrs(""GSDType"", ""ControlPanelNumber"", ""PLCSlotNumber"", ""DPNodeAddress"", ""PLCNumber"", ""DPDPCoupler"", ""AFDHubNumber"", ""ChannelNo"", ""DPPACoupler"", ""PANodeAddress"", ""RackNo"", ""SlotNo"", ""CalibratedRangeMin"", ""CalibratedRangeMax"", ""CalibratedRangeUnits"", ""ProcessRangeMin"", ""ProcessRangeMax"", ""ProcessRangeUnits"", ""RLPosition"")
     CROSS JOIN LATERAL ""fnGetDeviceDocumentsInColumns""(""View_Device_Instruments"".""Id"") docs(""DatasheetNumber"", ""SheetNumber"", ""HookupDrawing"", ""TerminationDiagram"", ""PIDNumber"", ""LayoutDrawing"", ""ArchitecturalDrawing"", ""FunctionalDescriptionDocument"", ""ProductProcurementNumber"")
     LEFT JOIN ""ControlSystemHierarchy"" h ON h.""ChildDeviceId"" = ""View_Device_Instruments"".""Id""
     LEFT JOIN ""Device"" pd ON h.""ParentDeviceId"" = pd.""Id""
     LEFT JOIN ""Tag"" pt ON pd.""TagId"" = pt.""Id""
     LEFT JOIN ""Tag"" skidtag ON skidtag.""Id"" = ""View_Device_Instruments"".""SkidTagId""
     LEFT JOIN ""Tag"" standtag ON standtag.""Id"" = ""View_Device_Instruments"".""StandTagId""
     LEFT JOIN ""Tag"" jbtag ON jbtag.""Id"" = ""View_Device_Instruments"".""JunctionBoxTagId""
     LEFT JOIN ""Tag"" ""panelTag"" ON ""panelTag"".""Id"" = ""View_Device_Instruments"".""PanelTagId""
	 GROUP BY ""View_Device_Instruments"".""Id"",
	 ""View_Device_Instruments"".""ProcessName"",
	 ""View_Device_Instruments"".""SubProcessName"",
	 ""View_Device_Instruments"".""StreamName"",
	 ""View_Device_Instruments"".""EquipmentCode"",
	 ""View_Device_Instruments"".""SequenceNumber"",
	 ""View_Device_Instruments"".""EquipmentIdentifier"",
	 ""View_Device_Instruments"".""TagName"",
	 ""View_Device_Instruments"".""ServiceDescription"",
	 ""View_Device_Instruments"".""LineVesselNumber"",
	 ""View_Device_Instruments"".""VendorSupply"",
	 skidtag.""TagName"",
     standtag.""TagName"",
     ""View_Device_Instruments"".""Manufacturer"",
     ""View_Device_Instruments"".""Model"",
     attrs.""CalibratedRangeMin"",
     attrs.""CalibratedRangeMax"",
     attrs.""CalibratedRangeUnits"",
     attrs.""ProcessRangeMin"",
     attrs.""ProcessRangeMax"",
     attrs.""ProcessRangeUnits"",
     attrs.""RLPosition"",
     docs.""DatasheetNumber"",
     docs.""SheetNumber"",
     docs.""HookupDrawing"",
     docs.""TerminationDiagram"",
     docs.""PIDNumber"",
     docs.""LayoutDrawing"",
     docs.""ArchitecturalDrawing"",
     docs.""FunctionalDescriptionDocument"",
     docs.""ProductProcurementNumber"",
     jbtag.""TagName"",
     ""View_Device_Instruments"".""NatureOfSignalName"",
     ""View_Device_Instruments"".""FailStateName"",
     attrs.""GSDType"",
     attrs.""ControlPanelNumber"",
     attrs.""PLCNumber"",
     attrs.""PLCSlotNumber"",
     ""panelTag"".""TagName"",
     attrs.""DPDPCoupler"",
     attrs.""DPPACoupler"",
     attrs.""AFDHubNumber"",
     attrs.""RackNo"",
     attrs.""SlotNo"",
     attrs.""ChannelNo"",
     attrs.""DPNodeAddress"",
     attrs.""PANodeAddress"",
     ""View_Device_Instruments"".""Revision"",
     ""View_Device_Instruments"".""RevisionChanges"",
     ""View_Device_Instruments"".""Zone"",
     ""View_Device_Instruments"".""Bank"",
     ""View_Device_Instruments"".""Service"",
     ""View_Device_Instruments"".""Variable"",
     ""View_Device_Instruments"".""Train"",
     ""View_Device_Instruments"".""WorkAreaPack"",
     ""View_Device_Instruments"".""System"",
     ""View_Device_Instruments"".""SubSystem"",
     ""View_Device_Instruments"".""HistoricalLogging"",
     ""View_Device_Instruments"".""HistoricalLoggingFrequency"",
     ""View_Device_Instruments"".""HistoricalLoggingResolution"",
     ""View_Device_Instruments"".""IsInstrument"",
     ""View_Device_Instruments"".""IsDeleted"",
     ""View_Device_Instruments"".""ProjectId"",
     ""View_Device_Instruments"".""IsActive"",
	 ""View_Device_Instruments"".""Type"";
	 
CREATE OR REPLACE VIEW public.""View_OMItem_InstrumentList""
 AS
 SELECT ""OMItem"".""Id"",
    ""OMItem"".""ItemId"",
    ""OMItem"".""ItemDescription"",
    ""OMItem"".""ParentItemId"",
    ""OMItem"".""AssetTypeId"",
    ""View_InstrumentListLive"".""DeviceId"",
    ""View_InstrumentListLive"".""Process No"",
    ""View_InstrumentListLive"".""Sub Process"",
    ""View_InstrumentListLive"".""StreamName"",
    ""View_InstrumentListLive"".""Equipment Code"",
    ""View_InstrumentListLive"".""Sequence Number"",
    ""View_InstrumentListLive"".""Equipment Identifier"",
    ""View_InstrumentListLive"".""TagName"" AS ""Tag"",
    ""View_InstrumentListLive"".""Instr Parent Tag"",
    ""View_InstrumentListLive"".""Service Description"",
    ""View_InstrumentListLive"".""Line / Vessel Number"",
    ""View_InstrumentListLive"".""Plant"",
    ""View_InstrumentListLive"".""Area"",
    ""View_InstrumentListLive"".""Vendor Supply"",
    ""View_InstrumentListLive"".""Skid Number"",
    ""View_InstrumentListLive"".""Stand Number"",
    ""View_InstrumentListLive"".""Manufacturer"",
    ""View_InstrumentListLive"".""Model Number"",
    ""View_InstrumentListLive"".""Calibrated Range (Min)"",
    ""View_InstrumentListLive"".""Calibrated Range (Max)"",
    ""View_InstrumentListLive"".""CR Units"",
    ""View_InstrumentListLive"".""Process Range (Min)"",
    ""View_InstrumentListLive"".""Process Range (Max)"",
    ""View_InstrumentListLive"".""PR Units"",
    ""View_InstrumentListLive"".""RL / Position"",
    ""View_InstrumentListLive"".""Datasheet Number"",
    ""View_InstrumentListLive"".""Sheet Number"",
    ""View_InstrumentListLive"".""Hook-up Drawing"",
    ""View_InstrumentListLive"".""Termination Diagram"",
    ""View_InstrumentListLive"".""P&Id Number"",
    ""View_InstrumentListLive"".""Layout Drawing"",
    ""View_InstrumentListLive"".""Architectural Drawing"",
    ""View_InstrumentListLive"".""Functional Description Document"",
    ""View_InstrumentListLive"".""Product Procurement Number"",
    ""View_InstrumentListLive"".""Junction Box Number"",
    ""View_InstrumentListLive"".""Nature Of Signal"",
    ""View_InstrumentListLive"".""Fail State"",
    ""View_InstrumentListLive"".""GSD Type"",
    ""View_InstrumentListLive"".""Control Panel Number"",
    ""View_InstrumentListLive"".""PLC Number"",
    ""View_InstrumentListLive"".""PLC Slot Number"",
    ""View_InstrumentListLive"".""Field Panel Number"",
    ""View_InstrumentListLive"".""DP/DP Coupler"",
    ""View_InstrumentListLive"".""DP/PA Coupler"",
    ""View_InstrumentListLive"".""AFD / Hub Number"",
    ""View_InstrumentListLive"".""Rack No"",
    ""View_InstrumentListLive"".""Slot No"",
    ""View_InstrumentListLive"".""Channel No"",
    ""View_InstrumentListLive"".""DP Node Address"",
    ""View_InstrumentListLive"".""PA Node Address"",
    ""View_InstrumentListLive"".""Revision"",
    ""View_InstrumentListLive"".""Revision Changes / Outstanding Comments"",
    ""View_InstrumentListLive"".""Zone"",
    ""View_InstrumentListLive"".""Bank"",
    ""View_InstrumentListLive"".""Service"",
    ""View_InstrumentListLive"".""Variable"",
    ""View_InstrumentListLive"".""Train"",
    ""View_InstrumentListLive"".""Work Area Pack"",
    ""View_InstrumentListLive"".""System Code"",
    ""View_InstrumentListLive"".""SubSystem Code"",
    ""View_InstrumentListLive"".""Historical Logging"",
    ""View_InstrumentListLive"".""Historical Logging Frequency"",
    ""View_InstrumentListLive"".""Historical Logging Resolution"",
    ""View_InstrumentListLive"".""IsInstrument"",
        CASE
            WHEN ""View_InstrumentListLive"".""IsActive"" IS NULL THEN ""OMItem"".""IsActive""
            ELSE ""View_InstrumentListLive"".""IsActive""
        END AS ""IsActive"",
        CASE
            WHEN ""View_InstrumentListLive"".""IsDeleted"" IS NULL THEN ""OMItem"".""IsDeleted""
            ELSE ""View_InstrumentListLive"".""IsDeleted""
        END AS ""IsDeleted"",
        CASE
            WHEN ""View_InstrumentListLive"".""ProjectId"" IS NULL THEN ""OMItem"".""ProjectId""
            ELSE ""View_InstrumentListLive"".""ProjectId""
        END AS ""ProjectId""
   FROM ""View_InstrumentListLive""
     FULL JOIN ""OMItem"" ON ""OMItem"".""ItemId""::text = ""View_InstrumentListLive"".""TagName""::text;

CREATE OR REPLACE VIEW public.""View_CountDPPADevices""
 AS
 SELECT ""ProjectId"",
    ""PLC Number"" AS ""PLC_Number"",
    ""PLC Slot Number"" AS ""PLC_Slot_Number"",
        CASE
            WHEN ""DP/DP Coupler"" IS NOT NULL THEN ""DP/DP Coupler""
            ELSE ""DP/PA Coupler""
        END AS ""DP_or_PA_Coupler"",
    ""AFD / Hub Number"" AS ""AFD___Hub_Number"",
        CASE
            WHEN ""DP/DP Coupler"" IS NOT NULL THEN count(*)
            ELSE 0::bigint
        END AS ""No__of_DP_Devices"",
        CASE
            WHEN ""DP/DP Coupler"" IS NULL THEN count(*)
            ELSE 0::bigint
        END AS ""No__of_PA_Devices""
   FROM ""View_InstrumentListLive""
  WHERE ""PLC Number"" IS NOT NULL AND ""PLC Slot Number"" IS NOT NULL AND ""DP/DP Coupler"" IS NOT NULL AND ""AFD / Hub Number"" IS NOT NULL OR ""PLC Number"" IS NOT NULL AND ""PLC Slot Number"" IS NOT NULL AND ""AFD / Hub Number"" IS NOT NULL AND ""DP/PA Coupler"" IS NOT NULL
  GROUP BY ""ProjectId"", ""PLC Number"", ""PLC Slot Number"", ""DP/DP Coupler"", ""DP/PA Coupler"", ""AFD / Hub Number"";

CREATE OR REPLACE VIEW public.""View_NatureOfSignalValidationFailures""
 AS
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
    list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE list.""Nature Of Signal""::text = 'DP'::text AND list.""DP Node Address"" IS NULL AND list.""IsDeleted"" = false
UNION
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
    list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE list.""Nature Of Signal""::text = 'PA'::text AND list.""PA Node Address"" IS NULL AND list.""IsDeleted"" = false
UNION
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
    list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE (list.""Nature Of Signal""::text = ANY (ARRAY['DI'::character varying::text, 'DO'::character varying::text, 'MO'::character varying::text, 'AI'::character varying::text, 'AO'::character varying::text, 'SDI'::character varying::text, 'SDO'::character varying::text, 'RTD'::character varying::text, 'SRTD'::character varying::text])) AND (list.""Rack No"" IS NULL OR list.""Slot No"" IS NULL OR list.""Channel No"" IS NULL) AND list.""IsDeleted"" = false;

END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DO $$
BEGIN

DROP VIEW public.""View_OMItem_InstrumentList"";
DROP VIEW public.""View_CountDPPADevices"";
DROP VIEW public.""View_NatureOfSignalValidationFailures"";

DROP VIEW public.""View_InstrumentListLive"";

CREATE OR REPLACE VIEW public.""View_InstrumentListLive""
 AS
 SELECT ""View_Device_Instruments"".""Id"" AS ""DeviceId"",
    ""View_Device_Instruments"".""ProcessName"" AS ""Process No"",
    ""View_Device_Instruments"".""SubProcessName"" AS ""Sub Process"",
    ""View_Device_Instruments"".""StreamName"",
    ""View_Device_Instruments"".""EquipmentCode"" AS ""Equipment Code"",
    ""View_Device_Instruments"".""SequenceNumber"" AS ""Sequence Number"",
    ""View_Device_Instruments"".""EquipmentIdentifier"" AS ""Equipment Identifier"",
    ""View_Device_Instruments"".""TagName"",
    pt.""TagName"" AS ""Instr Parent Tag"",
    ""View_Device_Instruments"".""ServiceDescription"" AS ""Service Description"",
    ""View_Device_Instruments"".""LineVesselNumber"" AS ""Line / Vessel Number"",
    NULL::text AS ""Plant"",
    NULL::text AS ""Area"",
    ""View_Device_Instruments"".""VendorSupply"" AS ""Vendor Supply"",
    skidtag.""TagName"" AS ""Skid Number"",
    standtag.""TagName"" AS ""Stand Number"",
    ""View_Device_Instruments"".""Manufacturer"",
    ""View_Device_Instruments"".""Model"" AS ""Model Number"",
    attrs.""CalibratedRangeMin"" AS ""Calibrated Range (Min)"",
    attrs.""CalibratedRangeMax"" AS ""Calibrated Range (Max)"",
    attrs.""CalibratedRangeUnits"" AS ""CR Units"",
    attrs.""ProcessRangeMin"" AS ""Process Range (Min)"",
    attrs.""ProcessRangeMax"" AS ""Process Range (Max)"",
    attrs.""ProcessRangeUnits"" AS ""PR Units"",
    attrs.""RLPosition"" AS ""RL / Position"",
    docs.""DatasheetNumber"" AS ""Datasheet Number"",
    docs.""SheetNumber"" AS ""Sheet Number"",
    docs.""HookupDrawing"" AS ""Hook-up Drawing"",
    docs.""TerminationDiagram"" AS ""Termination Diagram"",
    docs.""PIDNumber"" AS ""P&Id Number"",
    docs.""LayoutDrawing"" AS ""Layout Drawing"",
    docs.""ArchitecturalDrawing"" AS ""Architectural Drawing"",
    docs.""FunctionalDescriptionDocument"" AS ""Functional Description Document"",
    docs.""ProductProcurementNumber"" AS ""Product Procurement Number"",
    jbtag.""TagName"" AS ""Junction Box Number"",
    ""View_Device_Instruments"".""NatureOfSignalName"" AS ""Nature Of Signal"",
    ""View_Device_Instruments"".""FailStateName"" AS ""Fail State"",
    attrs.""GSDType"" AS ""GSD Type"",
    attrs.""ControlPanelNumber"" AS ""Control Panel Number"",
    attrs.""PLCNumber"" AS ""PLC Number"",
    attrs.""PLCSlotNumber"" AS ""PLC Slot Number"",
    ""panelTag"".""TagName"" AS ""Field Panel Number"",
    attrs.""DPDPCoupler"" AS ""DP/DP Coupler"",
    attrs.""DPPACoupler"" AS ""DP/PA Coupler"",
    attrs.""AFDHubNumber"" AS ""AFD / Hub Number"",
    attrs.""RackNo"" AS ""Rack No"",
    attrs.""SlotNo"" AS ""Slot No"",
    attrs.""ChannelNo"" AS ""Channel No"",
    attrs.""DPNodeAddress"" AS ""DP Node Address"",
    attrs.""PANodeAddress"" AS ""PA Node Address"",
    ""View_Device_Instruments"".""Revision"",
    ""View_Device_Instruments"".""RevisionChanges"" AS ""Revision Changes / Outstanding Comments"",
    ""View_Device_Instruments"".""Zone"",
    ""View_Device_Instruments"".""Bank"",
    ""View_Device_Instruments"".""Service"",
    ""View_Device_Instruments"".""Variable"",
    ""View_Device_Instruments"".""Train"",
    ""View_Device_Instruments"".""WorkAreaPack"" AS ""Work Area Pack"",
    ""View_Device_Instruments"".""System"" AS ""System Code"",
    ""View_Device_Instruments"".""SubSystem"" AS ""SubSystem Code"",
    ""View_Device_Instruments"".""HistoricalLogging"" AS ""Historical Logging"",
    ""View_Device_Instruments"".""HistoricalLoggingFrequency"" AS ""Historical Logging Frequency"",
    ""View_Device_Instruments"".""HistoricalLoggingResolution"" AS ""Historical Logging Resolution"",
    ""View_Device_Instruments"".""IsInstrument"",
    ""View_Device_Instruments"".""IsDeleted"",
    ""View_Device_Instruments"".""ProjectId"",
    ""View_Device_Instruments"".""IsActive""
   FROM ""View_Device_Instruments""
     CROSS JOIN LATERAL ""fnGetDeviceAttributesInColumns""(""View_Device_Instruments"".""Id"") attrs(""GSDType"", ""ControlPanelNumber"", ""PLCSlotNumber"", ""DPNodeAddress"", ""PLCNumber"", ""DPDPCoupler"", ""AFDHubNumber"", ""ChannelNo"", ""DPPACoupler"", ""PANodeAddress"", ""RackNo"", ""SlotNo"", ""CalibratedRangeMin"", ""CalibratedRangeMax"", ""CalibratedRangeUnits"", ""ProcessRangeMin"", ""ProcessRangeMax"", ""ProcessRangeUnits"", ""RLPosition"")
     CROSS JOIN LATERAL ""fnGetDeviceDocumentsInColumns""(""View_Device_Instruments"".""Id"") docs(""DatasheetNumber"", ""SheetNumber"", ""HookupDrawing"", ""TerminationDiagram"", ""PIDNumber"", ""LayoutDrawing"", ""ArchitecturalDrawing"", ""FunctionalDescriptionDocument"", ""ProductProcurementNumber"")
     LEFT JOIN ""ControlSystemHierarchy"" h ON h.""ChildDeviceId"" = ""View_Device_Instruments"".""Id"" AND h.""Instrument"" = true
     LEFT JOIN ""Device"" pd ON h.""ParentDeviceId"" = pd.""Id""
     LEFT JOIN ""Tag"" pt ON pd.""TagId"" = pt.""Id""
     LEFT JOIN ""Tag"" skidtag ON skidtag.""Id"" = ""View_Device_Instruments"".""SkidTagId""
     LEFT JOIN ""Tag"" standtag ON standtag.""Id"" = ""View_Device_Instruments"".""StandTagId""
     LEFT JOIN ""Tag"" jbtag ON jbtag.""Id"" = ""View_Device_Instruments"".""JunctionBoxTagId""
     LEFT JOIN ""Tag"" ""panelTag"" ON ""panelTag"".""Id"" = ""View_Device_Instruments"".""PanelTagId"";
	 
CREATE OR REPLACE VIEW public.""View_OMItem_InstrumentList""
 AS
 SELECT ""OMItem"".""Id"",
    ""OMItem"".""ItemId"",
    ""OMItem"".""ItemDescription"",
    ""OMItem"".""ParentItemId"",
    ""OMItem"".""AssetTypeId"",
    ""View_InstrumentListLive"".""DeviceId"",
    ""View_InstrumentListLive"".""Process No"",
    ""View_InstrumentListLive"".""Sub Process"",
    ""View_InstrumentListLive"".""StreamName"",
    ""View_InstrumentListLive"".""Equipment Code"",
    ""View_InstrumentListLive"".""Sequence Number"",
    ""View_InstrumentListLive"".""Equipment Identifier"",
    ""View_InstrumentListLive"".""TagName"" AS ""Tag"",
    ""View_InstrumentListLive"".""Instr Parent Tag"",
    ""View_InstrumentListLive"".""Service Description"",
    ""View_InstrumentListLive"".""Line / Vessel Number"",
    ""View_InstrumentListLive"".""Plant"",
    ""View_InstrumentListLive"".""Area"",
    ""View_InstrumentListLive"".""Vendor Supply"",
    ""View_InstrumentListLive"".""Skid Number"",
    ""View_InstrumentListLive"".""Stand Number"",
    ""View_InstrumentListLive"".""Manufacturer"",
    ""View_InstrumentListLive"".""Model Number"",
    ""View_InstrumentListLive"".""Calibrated Range (Min)"",
    ""View_InstrumentListLive"".""Calibrated Range (Max)"",
    ""View_InstrumentListLive"".""CR Units"",
    ""View_InstrumentListLive"".""Process Range (Min)"",
    ""View_InstrumentListLive"".""Process Range (Max)"",
    ""View_InstrumentListLive"".""PR Units"",
    ""View_InstrumentListLive"".""RL / Position"",
    ""View_InstrumentListLive"".""Datasheet Number"",
    ""View_InstrumentListLive"".""Sheet Number"",
    ""View_InstrumentListLive"".""Hook-up Drawing"",
    ""View_InstrumentListLive"".""Termination Diagram"",
    ""View_InstrumentListLive"".""P&Id Number"",
    ""View_InstrumentListLive"".""Layout Drawing"",
    ""View_InstrumentListLive"".""Architectural Drawing"",
    ""View_InstrumentListLive"".""Functional Description Document"",
    ""View_InstrumentListLive"".""Product Procurement Number"",
    ""View_InstrumentListLive"".""Junction Box Number"",
    ""View_InstrumentListLive"".""Nature Of Signal"",
    ""View_InstrumentListLive"".""Fail State"",
    ""View_InstrumentListLive"".""GSD Type"",
    ""View_InstrumentListLive"".""Control Panel Number"",
    ""View_InstrumentListLive"".""PLC Number"",
    ""View_InstrumentListLive"".""PLC Slot Number"",
    ""View_InstrumentListLive"".""Field Panel Number"",
    ""View_InstrumentListLive"".""DP/DP Coupler"",
    ""View_InstrumentListLive"".""DP/PA Coupler"",
    ""View_InstrumentListLive"".""AFD / Hub Number"",
    ""View_InstrumentListLive"".""Rack No"",
    ""View_InstrumentListLive"".""Slot No"",
    ""View_InstrumentListLive"".""Channel No"",
    ""View_InstrumentListLive"".""DP Node Address"",
    ""View_InstrumentListLive"".""PA Node Address"",
    ""View_InstrumentListLive"".""Revision"",
    ""View_InstrumentListLive"".""Revision Changes / Outstanding Comments"",
    ""View_InstrumentListLive"".""Zone"",
    ""View_InstrumentListLive"".""Bank"",
    ""View_InstrumentListLive"".""Service"",
    ""View_InstrumentListLive"".""Variable"",
    ""View_InstrumentListLive"".""Train"",
    ""View_InstrumentListLive"".""Work Area Pack"",
    ""View_InstrumentListLive"".""System Code"",
    ""View_InstrumentListLive"".""SubSystem Code"",
    ""View_InstrumentListLive"".""Historical Logging"",
    ""View_InstrumentListLive"".""Historical Logging Frequency"",
    ""View_InstrumentListLive"".""Historical Logging Resolution"",
    ""View_InstrumentListLive"".""IsInstrument"",
        CASE
            WHEN ""View_InstrumentListLive"".""IsActive"" IS NULL THEN ""OMItem"".""IsActive""
            ELSE ""View_InstrumentListLive"".""IsActive""
        END AS ""IsActive"",
        CASE
            WHEN ""View_InstrumentListLive"".""IsDeleted"" IS NULL THEN ""OMItem"".""IsDeleted""
            ELSE ""View_InstrumentListLive"".""IsDeleted""
        END AS ""IsDeleted"",
        CASE
            WHEN ""View_InstrumentListLive"".""ProjectId"" IS NULL THEN ""OMItem"".""ProjectId""
            ELSE ""View_InstrumentListLive"".""ProjectId""
        END AS ""ProjectId""
   FROM ""View_InstrumentListLive""
     FULL JOIN ""OMItem"" ON ""OMItem"".""ItemId""::text = ""View_InstrumentListLive"".""TagName""::text;

CREATE OR REPLACE VIEW public.""View_CountDPPADevices""
 AS
 SELECT ""ProjectId"",
    ""PLC Number"" AS ""PLC_Number"",
    ""PLC Slot Number"" AS ""PLC_Slot_Number"",
        CASE
            WHEN ""DP/DP Coupler"" IS NOT NULL THEN ""DP/DP Coupler""
            ELSE ""DP/PA Coupler""
        END AS ""DP_or_PA_Coupler"",
    ""AFD / Hub Number"" AS ""AFD___Hub_Number"",
        CASE
            WHEN ""DP/DP Coupler"" IS NOT NULL THEN count(*)
            ELSE 0::bigint
        END AS ""No__of_DP_Devices"",
        CASE
            WHEN ""DP/DP Coupler"" IS NULL THEN count(*)
            ELSE 0::bigint
        END AS ""No__of_PA_Devices""
   FROM ""View_InstrumentListLive""
  WHERE ""PLC Number"" IS NOT NULL AND ""PLC Slot Number"" IS NOT NULL AND ""DP/DP Coupler"" IS NOT NULL AND ""AFD / Hub Number"" IS NOT NULL OR ""PLC Number"" IS NOT NULL AND ""PLC Slot Number"" IS NOT NULL AND ""AFD / Hub Number"" IS NOT NULL AND ""DP/PA Coupler"" IS NOT NULL
  GROUP BY ""ProjectId"", ""PLC Number"", ""PLC Slot Number"", ""DP/DP Coupler"", ""DP/PA Coupler"", ""AFD / Hub Number"";

CREATE OR REPLACE VIEW public.""View_NatureOfSignalValidationFailures""
 AS
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
    list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE list.""Nature Of Signal""::text = 'DP'::text AND list.""DP Node Address"" IS NULL AND list.""IsDeleted"" = false
UNION
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
    list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE list.""Nature Of Signal""::text = 'PA'::text AND list.""PA Node Address"" IS NULL AND list.""IsDeleted"" = false
UNION
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
    list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE (list.""Nature Of Signal""::text = ANY (ARRAY['DI'::character varying::text, 'DO'::character varying::text, 'MO'::character varying::text, 'AI'::character varying::text, 'AO'::character varying::text, 'SDI'::character varying::text, 'SDO'::character varying::text, 'RTD'::character varying::text, 'SRTD'::character varying::text])) AND (list.""Rack No"" IS NULL OR list.""Slot No"" IS NULL OR list.""Channel No"" IS NULL) AND list.""IsDeleted"" = false;

END $$;");
        }
    }
}
