using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ICMD.EntityFrameworkCore.Migrations
{
    /// <inheritdoc />
    public partial class UpdateViewNatureSignal : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"CREATE OR REPLACE VIEW public.""View_NatureOfSignalValidationFailures""
 AS
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
	list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE list.""Nature Of Signal""::text = 'DP'::text AND list.""DP Node Address"" IS NULL AND list.""IsDeleted"" = false
UNION
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
	list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE list.""Nature Of Signal""::text = 'PA'::text AND list.""PA Node Address"" IS NULL AND list.""IsDeleted"" = false
UNION
 SELECT list.""DeviceId"",
    list.""Process No"",
    list.""Sub Process"",
    list.""StreamName"",
    list.""Equipment Code"",
    list.""Sequence Number"",
    list.""Equipment Identifier"",
    list.""TagName"",
    list.""Instr Parent Tag"",
    list.""Service Description"",
    list.""Line / Vessel Number"",
    list.""Plant"",
    list.""Area"",
    list.""Vendor Supply"",
    list.""Skid Number"",
    list.""Stand Number"",
    list.""Manufacturer"",
    list.""Model Number"",
    list.""Calibrated Range (Min)"",
    list.""Calibrated Range (Max)"",
    list.""CR Units"",
    list.""Process Range (Min)"",
    list.""Process Range (Max)"",
    list.""PR Units"",
    list.""RL / Position"",
    list.""Datasheet Number"",
    list.""Sheet Number"",
    list.""Hook-up Drawing"",
    list.""Termination Diagram"",
    list.""P&Id Number"",
    list.""Layout Drawing"",
    list.""Architectural Drawing"",
    list.""Functional Description Document"",
    list.""Product Procurement Number"",
    list.""Junction Box Number"",
    list.""Nature Of Signal"",
    list.""Fail State"",
    list.""GSD Type"",
    list.""Control Panel Number"",
    list.""PLC Number"",
    list.""PLC Slot Number"",
    list.""Field Panel Number"",
    list.""DP/DP Coupler"",
    list.""DP/PA Coupler"",
    list.""AFD / Hub Number"",
    list.""Rack No"",
    list.""Slot No"",
    list.""Channel No"",
    list.""DP Node Address"",
    list.""PA Node Address"",
    list.""Revision"",
    list.""Revision Changes / Outstanding Comments"",
    list.""Zone"",
    list.""Bank"",
    list.""Service"",
    list.""Variable"",
    list.""Train"",
    list.""Work Area Pack"",
    list.""System Code"",
    list.""SubSystem Code"",
    list.""Historical Logging"",
    list.""Historical Logging Frequency"",
    list.""Historical Logging Resolution"",
    list.""IsInstrument"",
    list.""IsDeleted"",
    list.""ProjectId"",
	list.""IsActive""
   FROM ""View_InstrumentListLive"" list
  WHERE (list.""Nature Of Signal""::text = ANY (ARRAY['DI'::character varying::text, 'DO'::character varying::text, 'MO'::character varying::text, 'AI'::character varying::text, 'AO'::character varying::text, 'SDI'::character varying::text, 'SDO'::character varying::text, 'RTD'::character varying::text, 'SRTD'::character varying::text])) AND (list.""Rack No"" IS NULL OR list.""Slot No"" IS NULL OR list.""Channel No"" IS NULL) AND list.""IsDeleted"" = false;
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
